name: Deploy Firebase Firestore

on:
  push:
    branches:
      - main
    paths:
      firebase.json
      firestore.rules
      firestore.indexes.json

jobs:
  deploy:
    runs-on: ubuntu-latest
  steps:
    - name: Checkout repo
      uses: action/checkout@v4
    
    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Deploy Firebase Rules
      run: firebase deploy --only firestore
      env: 
      FIREBASE_TOKEN:${{secrets.FIREBASE_TOKEN}}

